### ISSUE TITLE
SUGGESTED EDIT TO README

### ISSUE THREAD

**Issue by eDigirolamo** [MarkusMcNugen/docker-qBittorrentvpn#111]
DOCKER-compose 

qbittorrent:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbit
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - UMASK_SET=022 #optional
    volumes:
      - /YOUR CONFIG PATH:/config
      - /YOUR DLOAD PATH:/downloads
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped

**Comment by hatchcanon** [comment]
I agree that a compose example would be good. This is probably better though
```yml
version: "3.3"
services:
  qbittorrent:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbit
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=8.8.8.8,8.8.4.4
      - UMASK_SET=022 #optional
    volumes:
      - /YOUR CONFIG PATH:/config
      - /YOUR DLOAD PATH:/downloads
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    restart: unless-stopped
```
