### ISSUE TITLE
WebUI Only Works if VPN is Disabled

### ISSUE THREAD

**Issue by YabaiKai** [MarkusMcNugen/docker-qBittorrentvpn#112]
Hi Everyone,

I'm usually one to troubleshoot my own problems, but I've been plugging at this to no avail for many nights now. Only if I start the container with VPN_ENABLED set to "no" can I access the WebUI. I figure this must be a problem with the OpenVPN part of the container, but I just don't even know where to start. Only thing I can figure is that it is a problem with iptables. 

For what it's worth, I've tried several other configurations and had similar issues:
- Running a separate VPN container (ilteoood/docker-surfshark) and using it as the network_mode for a standard qBittorrent app
- Running other qBittorrent VPN images

Here's my docker-compose: 
```
services:
  qbittorrent:
    container_name: qBittorrentVPN
    volumes:
      - "/volume1/Docker/qBittorrentVPN/downloads:/downloads"
      - "/volume1/Docker/qBittorrentVPN/config:/config"
    environment:
      - VPN_ENABLED=yes
      - VPN_USERNAME=<username>
      - VPN_PASSWORD=<password>
      - "LAN_NETWORK=192.168.1.102/24"
      - "NAME_SERVERS=8.8.8.8,8.8.4.4"
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true
    image: markusmcnugen/qbittorrentvpn:latest
```
And attached is my log file. I see nothing all that fishy, though I do notice that in the iptables it mentions "192.168.1.0/24" instead of my LAN_NETWORK setting, "192.168.1.102". But further up you can see that it is loading in the LAN_NETWORK env variable correctly.

[qBittorrentVPN Log File.txt](https://github.com/MarkusMcNugen/docker-qBittorrentvpn/files/7682618/qBittorrentVPN.Log.File.txt)

Help me GitHub community, you're my only hope!
