### ISSUE TITLE
Unable to locate .ovpn

### ISSUE THREAD

**Issue by BertMacklinFBl** [MarkusMcNugen/docker-qBittorrentvpn#128]
Container launch fails with the same error: 

```
qbittorrentvpn    | 2022-04-17 03:05:36.240176 [info] VPN_ENABLED defined as 'yes'
qbittorrentvpn    | 2022-04-17 03:05:36.282398 [crit] No OpenVPN config file located in /config/openvpn/ (ovpn extension), please download from your VPN provider and then restart this container, exiting...
qbittorrentvpn exited with code 1
```

I'm using Mullvad and downloaded the android .ovpn file. I've tried placing it in a number of locations.

Compose file:

```
version: "2"
services:
        qbittorrentvpn:
                container_name: qbittorrentvpn
                image: markusmcnugen/qbittorrentvpn
                privileged: yes
                environment:
                        - VPN_USERNAME=XXXXXXXXXXXXXXXX
                        - VPN_ENABLED=yes
                        - LAN_NETWORK=192.168.50.0/24
                        - NAME_SERVERS=8.8.8.8,8.8.4.4
                        - PUID=0
                        - PGID=0
                volumes:
                        - /mnt/firespray/compose/docker-qbittorrentvpn/config/openvpn/config
                        - /mnt/firespray/torrents/downloads
                ports:
                        - 8080:8080
                        - 8999:8999
                        - 8999:8999/udp
```
