### ISSUE TITLE
Webui Broken

### ISSUE THREAD

**Issue by ozdeadmeat** [MarkusMcNugen/docker-qBittorrentvpn#149]
Have tried to get this working with a VPN enabled or Disabled. Can't get the webui to show up at all.

Here is my compose file:

version: "3"
services:
# qbittorrent  
  qbittorrent:
    image: markusmcnugen/qbittorrentvpn:latest
    container_name: qbittorrent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
     - PUID=1000
     - PGID=1000
     - UMASK=002
     - TZ=Australia/Sydney
     - WEBUI_PORT_ENV=8282
     - INCOMING_PORT_ENV=6888
     - VPN_ENABLED=no
     - VPN_USERNAME=<removed>
     - VPN_PASSWORD=<removed>
     - LAN_NETWORK=10.4.78.0/24
     - NAME_SERVERS=8.8.8.8,8.8.4.4
    volumes:
     - qbittorrent-Config:/config
     - /mnt/qbittorrent/downloads:/downloads
    ports:
     - 8282:8282
     - 6888:6888
     - 6888:6888/udp
    networks:
     - qbittorrent-net
    restart: unless-stopped

# shared config VOLUMES
volumes:
  qbittorrent-Config:
    name: qbittorrent-Config
# shared config NETWORK
networks:
 qbittorrent-net:
  name: qbittorrent-net

The error received whether on the same IP address range as the docker host or on a different IP address range is the same

ERR_CONNECTION_REFUSED

**Comment by johncsuti** [comment]
https://github.com/MarkusMcNugen/docker-qBittorrentvpn/issues/125#issuecomment-1251113909

**Comment by Ohmslaw79** [comment]
`I figured it out, see edit for the solution.` I am also having this issue but I am using the correct environment variable names. I have attached my compose, env file, and logs. I can see that it is picking up the correct ports in the logs. But after I launch it I go https://<serverIP>:8888 and get nothing

```
version: '3.3'
services:
    qbittorrentvpn:
        container_name: "qbittorrent"
        privileged: true
        volumes:
            - '/var/qbit-config:/config'
            - '/media/qbit-downloads:/downloads'
        ports:
            - '8888:8888'
            - '8889:8889'
            - '8889:8889/udp'
        env_file:
          - stack.env
        image: markusmcnugen/qbittorrentvpn
        networks:
          - npm-network
networks:
  npm-network:
    external: true
```

```
VPN_ENABLED=yes
LAN_NETWORK=192.168.0.1/24
NAME_SERVERS=192.168.0.110,8.8.8.8,8.8.4.4,1.1.1.1
PUID=99
PGID=100
WEBUI_PORT=8888
INCOMING_PORT=8889
```

EDIT: Going to leave this just in case someone's new to networking like me and managed to make the same mistake as me. I just realized I misdefined my local network. I put 192.168.0.1/24, not right. 192.168.0.0/24 is what I needed to define my network
