### ISSUE TITLE
Can't access WebUI - with or without VPN

### ISSUE THREAD

**Issue by baykalokandemir** [MarkusMcNugen/docker-qBittorrentvpn#169]
Hi! As the title suggests, I cant reach the web UI from my local network. The problem persists with or without VPN enabled. Here's my docker-compose.yml

```yml
qbittorrentvpn:
    image: markusmcnugen/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    cap_add:
        - NET_ADMIN
    environment:
      - VPN_ENABLED=no
      - LAN_NETWORK=192.168.178.0/24
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    volumes:
      - ~/docker/config/qbittorrentvpn:/config
      - /shitbox/NAS/downloads:/downloads
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped    
 ```   
and here is the log:

```
2024-04-26 22:06:32.518707 [info] VPN_ENABLED defined as 'no'
2024-04-26 22:06:32.537985 [warn] !!IMPORTANT!! You have set the VPN to disabled, you will NOT be secure!
Adding 1000 group
Adding 1000 user
2024-04-26 22:06:32.596255 [warn] UMASK not defined (via -e UMASK), defaulting to '002'
2024-04-26 22:06:32.614250 [info] Starting qBittorrent daemon...
Log file /config/qBittorrent/data/logs/qbittorrent-daemon.log doesn't exist. Creating it...
Logfile created. Logging to /config/qBittorrent/data/logs/qbittorrent-daemon.log
2024-04-26 22:06:33.634763 [info] qBittorrent PID:
2024-04-26 22:06:33.640074 [info] Started qBittorrent daemon successfully..
```

Any help would be appreciated, I've been going at this for hours. I saw that a lot of people with the same problem managed to fix theirs with the correct LAN_NETWORK and ports but im pretty sure i got mine correctly and haven't made any progress.

**Comment by neonoatmeal** [comment]
I'm having the same issue. Any help would be greatly appreciated.

**Comment by aaronzdavis** [comment]
I'm also experiencing this.

**Comment by neonoatmeal** [comment]
> I'm also experiencing this.

It's likely an issue with the qbittorrentvpn image. To bypass this, I used a normal version of qbittorrent but created another docker container, running gluetun, to route my traffic through. 

Edit: For anyone having the same issue, [here](https://github.com/qdm12/gluetun) is where you can find the gluetun docker build and below is a copy of my docker-compose file with relevant pieces:

```
services:
    gluetun:
        image: qmcgaw/gluetun:latest
        cap_add:
            - NET_ADMIN
        volumes:
            - /opt/docker/plex/gluetun:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=private internet access
            - OPENVPN_USER=PIA_USERNAME
            - OPENVPN_PASSWORD=PIA_PASSWORD
            - SERVER_REGIONS=US East
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        restart: unless-stopped
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        restart: unless-stopped
        volumes:
            - /opt/docker/plex/qbittorrent:/config
            - /home/data/downloads:/data/downloads # Change this to your downloads directory
        environment:
            - PUID=1000 # Change this to your user ID
            - PGID=1000 # Change this to your group ID
            - TZ=Etc/UTC
            - WEBUI_PORT=8080
            - TORRENTING_PORT=6881
```

**Comment by tmac12** [comment]
Thanks @neonoatmeal for your suggestion, however with the latest version of the images it need a few modifications.
Here is my working file:
```yaml

services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        # line above must be uncommented to allow external containers to connect.
        # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
        cap_add:
            - NET_ADMIN
        volumes:
            - /dev/net/tun:/dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=private internet access
            - OPENVPN_USER=PIA_USERNAME
            - OPENVPN_PASSWORD=PIA_PASSWORD
            - SERVER_REGIONS=US East
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
            - 8888:8888/tcp # HTTP proxy
            - 8388:8388/tcp # Shadowsocks
            - 8388:8388/udp # Shadowsocks
        restart: unless-stopped
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        restart: unless-stopped
        volumes:
            - /opt/docker/plex/qbittorrent:/config
            - /home/data/downloads:/downloads # Change this to your downloads directory
        environment:
            - PUID=1000 # Change this to your user ID
            - PGID=1000 # Change this to your group ID
            - TZ=Etc/UTC
            - WEBUI_PORT=8080
            - TORRENTING_PORT=6881
```
