### ISSUE TITLE
Web port not respected

### ISSUE THREAD

**Issue by Altycoder** [MarkusMcNugen/docker-qBittorrentvpn#33]
I have another service listening on port 8080 so I need to change the webui to another port, I chose 8081 which is free.

However if I pass 8081 as WEBUI_PORT (or WEBUI_PORT_ENV) and specify ports 8081:8081 I can see in the logs via portainer:

2019-10-31 11:38:55.178852 [info] WebUI port defined as 
2019-10-31 11:38:55.253496 [info] LAN Network defined as 192.168.1.0/24

(i.e. no port)

and lower down in the log in the iptables section:

-P INPUT DROP
-P FORWARD ACCEPT
-P OUTPUT DROP
-A INPUT -i tun0 -j ACCEPT
-A INPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --sport 1198 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A INPUT -s 192.168.1.0/24 -i eth0 -p tcp -m tcp --dport 8999 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
-A OUTPUT -s 172.18.0.0/16 -d 172.18.0.0/16 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 1198 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A OUTPUT -d 192.168.1.0/24 -o eth0 -p tcp -m tcp --sport 8999 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT

i.e. port 8080 is still being used.

Here is my entire docker-compose:

    torrentserver:
    container_name: torrentserver
    image: markusmcnugen/qbittorrentvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /<redacted>/:/data
      - /<redacted>/:/config
    ports:
      - 8081:8081
      - 8999:8999
      - 8999:8999/udp      
    environment:
      - VPN_ENABLED=yes
      - VPN_USERNAME=<redacted>
      - VPN_PASSWORD=<redacted>
      - NAME_SERVERS=1.1.1.1,8.8.8.8
      - LAN_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=1000
      - UMASK=777
      - WEBUI_PORT=8081
      - INCOMING_PORT_ENV=8999

**Comment by nimblebytes** [comment]
I have run into the same issue.

I have narrowed down the problem to the following line of code in file `/qbittorrent/start.sh`
`sed -i "${LINE_NUM}s@.*@WebUI\\Port=${WEBUI_PORT}@" /config/qBittorrent/config/qBittorrent.conf`

if you run the container the first time the config file variable get mangled and results in the following:
`WebUIPort=[WEBUI_PORT]`
instead of
`WebUI\Port=[WEBUI_PORT]` - backslash is/was missing

Running the container the second time fixes the issued, because a different line of code inserts the correct value at the bottom of the file (instead of search and replace with sed)

The sed expression seems correctly escape the bashslash to me. I try and experiment a bit more, to see why it fails.

P.S. `Connection\PortRangeMin=[INCOMING_PORT]` is also affected as it uses the same code structure in the same file

**Comment by Altycoder** [comment]
I still can't get this working.  I've managed to get a different image using Transmission to work but would prefer qbittorrent instead as it has more flexibility

**Comment by Altycoder** [comment]
OK I've managed to crack it by changing both the mapped and exposed webui port and the webui_port to something different then removing the container and recreating it.  Just restarting doesn't pick up the changes.

**Comment by Waldorf3** [comment]
I would leave this open as it is still a problem now in 2022.

Another thing I think is unclear from the documentation is, if you want to change the UI port from 8080 you need to change both the internal and external port as well as the environment variable, so:

```
services:
  qbittorrent-openvpn:
    container_name: qbittorrentvpn
    volumes:
    - ./config/:/config
    - CHANGE:/downloads
    environment:
    - VPN_ENABLED=yes
    - VPN_USERNAME=CHANGE
    - VPN_PASSWORD=CHANGE
    - LAN_NETWORK=CHANGE
    - NAME_SERVERS=9.9.9.9,1.1.1.2
    - PUID=33
    - PGID=33
    - UMASK=022
    - WEBUI_PORT=8081
    ports:
    - 8081:8081
    - 8999:8999
    - 8999:8999/udp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
    - 9.9.9.9
    - 1.1.1.2
    image: markusmcnugen/qbittorrentvpn
    restart: unless-stopped
```
